# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QPandas
                                 A QGIS plugin
 Pandas utilities in QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-07
        copyright            : (C) 2020 by Matteo Ghetta (Faunalia)
        email                : matteo.ghetta@faunalia.eu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Matteo Ghetta (Faunalia)'
__date__ = '2022-05-13'
__copyright__ = '(C) 2022 by Matteo Ghetta (Faunalia)'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import pandas as pd

from qgis.core import QgsFeatureRequest


def dataframe_from_layer(layer):
    """
    Args:
        layer (QgsVectorLayer): QgsVectorLayer that will be transformed into a
        pandas DataFrame
    
    Returns:
        df [pandas DataFrame]: [Pandas DataFrame]
    """

    # QgsFeatureRequest to speed up the loop avoiding geometries
    request = QgsFeatureRequest()
    request.setFlags(QgsFeatureRequest.NoGeometry)

    # get field names used as column names in the Pandas DataFrame
    names = [f.name() for f in layer.fields()]

    # get attributes from features
    data = [i.attributes() for i in layer.getFeatures(request)]

    # create the DataFrame
    df = pd.DataFrame(data, columns=names)

    return df


class PlotType:

    def __init__(self, x, y):
        self.x = x
        self.y = y