name: Test plugin

on:
  push:
    paths:
    - "DataPlotly/**"
    - ".github/workflows/test_plugin.yaml"
  pull_request:
    paths:
    - "DataPlotly/**"
    - ".github/workflows/test_plugin.yaml"

env:
  # plugin name/directory where the code for the plugin is stored
  PLUGIN_NAME: DataPlotly
  # python notation to test running inside plugin
  TESTS_RUN_FUNCTION: DataPlotly.test_suite.test_package
  # Docker settings
  DOCKER_IMAGE: qgis/qgis


jobs:

  Test-plugin-DataPlotly:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        qgis_version: [
          "3.34",
          "3.40",
        ]
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Running tests
        run: >-
          docker run --quiet --rm --name qgis-DataPlotly-tests
          --network host
          --user $(id -u):$(id -g)
          --mount type=bind,source=$GITHUB_WORKSPACE,target=/src
          --workdir /src
          --env QGIS_VERSION=${{ matrix.qgis_version }}
          $DOCKER_IMAGE:${{ matrix.qgis_version }} .docker/run-tests.sh

  Check-code-quality:
    runs-on: ubuntu-latest
    steps:

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          pip install -r REQUIREMENTS_TESTING.txt
          pip install pylint pycodestyle

      - name: Pylint
        run: make pylint

      - name: Pycodestyle
        run: make pycodestyle
